---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalsg/marvin # todo: Change to milliways here...
    tag: '0.1.1'

inputs:
  - name: marvin-source
  - name: milliways-source

outputs:
  - name:  milliways-build

run:
  path: milliways-source/ci/tasks/integration.sh
